---
title: "R Notebook"
output: github_document
---
```{bash, eval = FALSE}
wget -i url_data
```


```{r}
#charger les librairies 
library(dada2)
library(phyloseq)
library(DECIPHER)
library(phangorn)
library(ggplot2)
library(gridExtra)
library(shiny)
library(miniUI)
#library(caret)
library(pls)
library(e1071)
library(ggplot2)
library(randomForest)
library(dplyr)
library(ggrepel)
#library(nlme)
library(devtools)
library(reshape2)
library(PMA)
#library(structSSI)
library(ade4)
library(ggnetwork)
library(intergraph)
library(scales)
library(phyloseqGraphTest)
library(genefilter)
library(impute)
```

```{r}
#la variable (path) indique le chemin qui permettra d’accéder aux objets dont nous allons avoir besoin.
path <- "/home/rstudio/CC3/data"
```

```{r}
fnFs <- sort(list.files(path, pattern="_R1.fastq.gz.1", full.names = TRUE))
fnRs <- sort(list.files(path, pattern="_R2.fastq.gz.1", full.names = TRUE))
#créer une variable qui extrait le nom de cet échantillon.
sample.names <- sapply(strsplit(basename(fnFs), "_R"), `[`, 1)
```

```{r}
#Cette étape permet de visualiser la qualité des séquences grâce au Q score associé à chaque nucléotide
plotQualityProfile(fnFs[1:2])
plotQualityProfile(fnRs[1:2])
```


```{r}
# créer des objets (filtFs et filtRs) pour stoquer les séquences filtrées.
filtFs <- file.path(path, "filtered", paste0(sample.names, "_F_filt.fastq.gz"))
filtRs <- file.path(path, "filtered", paste0(sample.names, "_R_filt.fastq.gz"))
names(filtFs) <- sample.names
names(filtRs) <- sample.names
```

```{r}
#Dans cette étapes Nous utiliserons les paramètres de filtrage standard
out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(180,200),
              maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
              compress=TRUE, multithread=TRUE)
head(out)
```
```{r }
errF <- learnErrors(filtFs, multithread=TRUE)
```

```{r}
errR <- learnErrors(filtRs, multithread=TRUE)
```
```{r}
plotErrors(errF, nominalQ=TRUE)
```
```{r}
dadaFs <- dada(filtFs, err=errF, multithread=TRUE)
```
```{r}
dadaRs <- dada(filtRs, err=errR, multithread=TRUE)
```
```{r}
dadaFs[[1]]
```
```{r}
dadaRs[[1]]
```
```{r}
mergers <- mergePairs(dadaFs, filtFs, dadaRs, filtRs, verbose=TRUE)
head(mergers[[1]])
```
```{r}
seqtab <- makeSequenceTable(mergers)
dim(seqtab)
```
```{r}
table(nchar(getSequences(seqtab)))
```
```{r}
seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=TRUE, verbose=TRUE)
dim(seqtab.nochim)
```
```{r}
sum(seqtab.nochim)/sum(seqtab)
```
```{r}
#Tableau de suivi,voir combien de séquences ont été éliminées à chaque étape
getN <- function(x) sum(getUniques(x))
track <- cbind(out, sapply(dadaFs, getN), sapply(dadaRs, getN), sapply(mergers, getN), rowSums(seqtab.nochim))
colnames(track) <- c("input", "filtered", "denoisedF", "denoisedR", "merged", "nonchim")
rownames(track) <- sample.names
head(track)

```
```{bash}
#attribuer une taxonomie aux variants de séquence
wget https://zenodo.org/record/4587955/files/silva_nr99_v138.1_train_set.fa.gz?download=1
```

```{r}
taxa <- assignTaxonomy(seqtab.nochim, "silva_nr99_v138.1_train_set.fa.gz?download=1", multithread=TRUE)
```

```{r}
#Inspecter les affectations taxonomiques
taxa.print <- taxa
rownames(taxa.print) <- NULL
head(taxa.print)
```

```{r}
library(phyloseq); packageVersion("phyloseq")
library(Biostrings); packageVersion("Biostrings")
library(ggplot2); packageVersion("ggplot2")
```
```{r}
theme_set(theme_bw())
```
# Les séquences d'ADN mise en ligne par l'auteur étaient dans un seul dossier (Ne sont pas séparées selon les régions d'étude), cela m'a empéché d'établir un graphique qui montre la taxonomie des microorganismes selon la région.






